[package]
name = "profile-microsoft"
version = "0.1.0"
edition = "2021"

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi", features = [
    "kurbo",
] }
skrifa = { workspace = true }
read-fonts = { workspace = true }
regex = "1.10.6"
