[package]
name = "profile-universal"
version = "0.1.0"
edition = "2021"
authors =  [
    "Simon Cozens <simon@simon-cozens.org>",
    "Felipe Sanches <juca@members.fsf.org>",
]

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi" }
read-fonts = "0.19.3"
skrifa = "0.19.3"
pluginator = "1.0.1"
write-fonts = "0.27.0"
font-types = "0.5.5"