[package]
name = "profile-universal"
version = "0.1.0"
edition = "2021"
authors =  [
    "Simon Cozens <simon@simon-cozens.org>",
    "Felipe Sanches <juca@members.fsf.org>",
]

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi" }
read-fonts = {workspace = true}
write-fonts = {workspace = true}
font-types = {workspace = true}
skrifa = {workspace = true}
regex = "1.10.6"
itertools = "0.13.0"