[package]
name = "profile-googlefonts"
version = "0.1.0"
edition = "2021"

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi" }
protobuf = "3.5.0"
pluginator = "1.0.1"

chrono="0.4.38"  # For metadata date checks

[build-dependencies]
protobuf-codegen = "3.5.0"
