[package]
name = "profile-testplugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["dylib"]

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi" }
skrifa = "0.15.0"
read-fonts = "0.15.0"
pluginator = "1.0.1"
