[package]
name = "profile-testplugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["dylib"]

[dependencies]
fontspector-checkapi = { path = "../fontspector-checkapi" }
pluginator = "1.0.1"
toml = "0.8.14"
